/*-----------
玩法很简单，只要仿照下面两个例子：
1、定义一个ID，比如：zhangsan
2、完成三个过程：
		初始化：	zhangsan_INIT
		出拳：		zhangsan_COME
		查看结果：	zhangsan_COMEOUT
3、调用主控过程	EXEC GAME_HUAQUAN 'zhangsan','lisi'
4、等待系统结果显示
-----------*/

/*------------酒鬼LISI-------*/

--初始化
IF(OBJECT_ID('LISI_INIT') IS NOT NULL) 
DROP PROCEDURE LISI_INIT
GO
CREATE PROCEDURE LISI_INIT
AS
BEGIN
	DECLARE @EMPTY INT
	--这机器人随时开战
END
GO

--出拳
IF(OBJECT_ID('LISI_COME') IS NOT NULL) 
DROP PROCEDURE LISI_COME
GO
CREATE PROCEDURE LISI_COME(@FINGER INT OUT,@SUM INT OUT)
AS
BEGIN
	SET @SUM=ABS(CHECKSUM(NEWID()))%11;
	IF(@SUM<5) --别犯规
		SET @FINGER=ABS(CHECKSUM(NEWID()))%(@SUM+1)
	ELSE
		SET @FINGER=@SUM-5+ABS(CHECKSUM(NEWID()))%6
END
GO
---查看比赛结果
IF(OBJECT_ID('LISI_COMEOUT') IS NOT NULL) 
DROP PROCEDURE LISI_COMEOUT
GO
CREATE PROCEDURE LISI_COMEOUT(
@SELFFINGER INT,
@SEFLSUM INT,
@SELFRESULT VARCHAR(10),
@OTERFINGER INT,
@OTHERSUM INT,
@OTHERRESULT VARCHAR(10))
AS
BEGIN
	--这机器人不关心比赛结果
	DECLARE @EMPTY INT
END
GO