SELECT SUBSTRING(E.ENAME, 1, ITER.POS) AS C
  FROM (SELECT ENAME
          FROM EMP
         WHERE ENAME = 'KING'
       ) AS E
 CROSS JOIN (SELECT ID AS POS
          FROM T10
       ) AS ITER
 WHERE ITER.POS <= LEN(E.ENAME);