DECLARE @T TABLE (P VARCHAR (MAX ), X INT , Y INT )
INSERT INTO @T 
SELECT 'P11' , 1 , 1 UNION 
SELECT 'P12' , 1 , 2 UNION 
SELECT 'P13' , 1 , 3 UNION 
SELECT 'P14' , 1 , 4 UNION 
SELECT 'P21' , 2 , 1 UNION 
SELECT 'P22' , 2 , 2 UNION 
SELECT 'P23' , 2 , 3 UNION 
SELECT 'P24' , 2 , 4 UNION 
SELECT 'P31' , 3 , 1 UNION 
SELECT 'P32' , 3 , 2 UNION 
SELECT 'P33' , 3 , 3 UNION 
SELECT 'P34' , 3 , 4 UNION 
SELECT 'P42' , 4 , 2 UNION 
SELECT 'P43' , 4 , 3;

WITH T(PSTART, P, C, X, Y) AS 
(
    SELECT P, P, 1, X, Y
      FROM @T 
     UNION ALL 
    SELECT T.PSTART, T.P + '¡ú' + T_NEXT.P, C + 1, T_NEXT.X, T_NEXT.Y
      FROM @T T_NEXT, T
     WHERE ((ABS(T_NEXT.X - T.X) = 1 AND ABS(T_NEXT.Y - T.Y) = 2) OR
            (ABS(T_NEXT.X - T.X) = 2 AND ABS(T_NEXT.Y - T.Y) = 1))
       AND (CHARINDEX(T_NEXT.P, T.P) = 0 OR (C = 14 AND T_NEXT.P = T.PSTART))
)
SELECT P FROM T WHERE C = 15;